### ISSUE TITLE
API conflicts with activerecord

### ISSUE THREAD

**Issue by sebbacon** [resgraph/acts-as-dag#10]
There's a `created?` method in ActiveRecord that is also injected into `acts_as_dag` nodes.

I'm not sure what the sensible way of fixing this should be as fixing it by renaming the `acts_as_dag` version will break anything that relies on the existing behaviour.

In ActiveRecord 3.1.8 this conflict means it's impossible to create links, as [`primary_key=`](https://github.com/rails/rails/blob/3-1-stable/activerecord/lib/active_record/attribute_methods/primary_key.rb#L57) tries to call the ActiveRecord `connected?` method, and fails with `ArgumentError: wrong number of arguments (0 for 2)`.

**Comment by resgraph** [comment]
Thanks for the report. Looking into it.

**Comment by nigelr** [comment]
Just noticed that the connected? method is also in conflict with ActiveRecord::Base

**Comment by laserlemon** [comment]
I'm also experiencing the collision with Active Record's API on the `connected?` method. While the tests currently pass, acts-as-dag is terribly broken using Active Record 3.1 (and I suspect 3.2).

**Comment by laserlemon** [comment]
I suggest ripping out the `connected?` method in favor of using `find_link` directly. Also, the `connect` and `connect!` methods can be removed in order to help avoid future collisions. This would be a backwards-incompatible change so would warrant a v3 release, but would make acts-as-dag work with Rails 3.1+. We'll submit a PR shortly. Thank you!
